<?php
$escape = $this->plugin('escapeHtml');
$translate = $this->plugin('translate');
?>
<nav class="navbar navbar-light bg-light navbar-expand-lg" aria-label="<?php echo $escape($translate('Main navigation')); ?>">
    <div class="container-fluid">
        <a href="<?php echo $escape($site->url()); ?>" class="navbar-brand"><?php echo $escape($site->title()); ?></a>
        <button class="navbar-toggler" type="button" aria-controls="site-nav" aria-expanded="false" aria-label="<?php echo $escape($translate('Toggle Menu')); ?>">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="site-nav">
            <?php echo $site->publicNav()->menu()->setPartial('common/navigation.phtml')->render(); ?>
            <div class="d-flex">
                <?php echo $this->partial('common/search-form'); ?>
            </div>
        </div>
    </div>
</nav>
