<?php
$escape = $this->plugin('escapeHtml');
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;
?>
<?php if ($itemSets): ?>
<section class="item-sets">
    <h3 class="section-title"><?php echo $escape($this->translate('Item sets')); ?></h3>
    <ul class="item-set-links">
        <?php foreach ($itemSets as $itemSet): ?>
        <li><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(null, $valueLang); ?></a></li>
        <?php endforeach; ?>
    </ul>
</section>
<?php endif; ?>
