<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $name
 * @var array $facetValues With value, count, active, label and url when needed.
 * @var array $options
 * @var array|null $tree For item sets tree or thesaurus. Don't contain data from item sets not in the site.
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$isFacetModeDirect = in_array($options['mode'] ?? null, ['link', 'js']);
$displayCount = !empty($options['display_count']);

$isTree = is_array($tree);
?>

<div class="facet-items">
    <?php foreach ($facetValues as $facetValue):
        $escapedValue = $escapeAttr($facetValue['value']);
        $escapedId = $name . '[]' . $escapedValue;
        $label = $displayCount
            ? sprintf('%s <span class="badge bg-secondary ms-1">%d</span>', $escape($facetValue['label']),  $facetValue['count'])
            : $escape($facetValue['label']);
        $treeVal = $isTree ? $tree[$facetValue['value']] ?? null : null;
        $treeValAttrs = $treeVal ? sprintf(' data-value="%s" data-parent="%s" data-level="%s"', $treeVal['id'], $treeVal['parent'], $treeVal['level']) : '';
    ?>
    <div class="form-check facet-item <?= $facetValue['active'] ? 'active' : 'inactive' ?>"<?= $treeValAttrs ?>>
        <input class="form-check-input" type="checkbox" name="<?= "facet[$name][]" ?>" id="<?= $escapedId ?>" value="<?= $escapedValue ?>"<?= $isFacetModeDirect ? ' data-url="' . $escapeAttr($facetValue['url']) . '"' : '' ?><?= $facetValue['active'] ? ' checked="checked"' : '' ?>/>
        <label class="form-check-label" for="<?= $escapedId ?>"><?= $label ?></label>
    </div>
    <?php endforeach; ?>
</div>
